(() => {
  const COLORS = ['mint','yellow','blue','purple','pink','gray'];
  const COLOR_LABELS = {mint:'Mentazöld',yellow:'Sárga',blue:'Kék',purple:'Lila',pink:'Rózsaszín',gray:'Szürke'};
  const state = { items: [], editingId: null, color: 'mint' };
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const currentUser = () => window.state?.currentUser || SafeStorage.get(CURRENT_USER_KEY) || null;

  function card(item){return `<article class="info-card info-card--${esc(item.color)}" data-info-id="${item.id}"><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><button class="info-card__menu" type="button" aria-label="Műveletek" data-info-action="menu">⋮</button></article>`;}
  function render(){const p=document.getElementById('placeholder-view'); if(!p)return; p.innerHTML=`<section class="info-view" aria-label="Infók"><div class="info-view__header"><div class="info-kicker">Hasznos tudnivalók</div><h2>Infók</h2><p>Fontos információk az utazáshoz, egy helyen.</p></div><div class="info-list" id="info-list">${state.items.length?state.items.map(card).join(''):`<div class="info-empty">${icon('info',{size:38})}<h3>Még nincs infó</h3><p>Adj hozzá egy fontos tudnivalót a + gombbal.</p></div>`}</div><button class="info-add" id="info-add" type="button" aria-label="Új infó hozzáadása"><span>+</span><small>Új infó</small></button></section>`;}
  async function load(){const {data,error}=await supabase.from('info_items').select('*').order('created_at',{ascending:true}); if(error)throw error; state.items=data||[]; render();}
  function modal(item=null){state.color=item?.color||'mint'; const options=COLORS.map(c=>`<button type="button" class="info-color-option ${state.color===c?'is-selected':''}" data-info-color="${c}">${COLOR_LABELS[c]}</button>`).join(''); const host=document.createElement('div');host.id='info-modal-host';host.innerHTML=`<div class="info-modal-backdrop" id="info-modal-backdrop"></div><section class="info-modal" role="dialog" aria-modal="true"><div class="info-modal__header"><button class="bring-back" id="info-cancel" type="button">${icon('chevronLeft',{size:22})}</button><div><div class="info-kicker">${item?'Szerkesztés':'Új infó'}</div><h2>${item?'Infó módosítása':'Új infó hozzáadása'}</h2></div></div><div class="info-form"><label>Cím<input id="info-title" maxlength="120" value="${esc(item?.title||'')}" placeholder="Pl. Indulás időpontja"></label><label>Leírás<textarea id="info-description" maxlength="1000" placeholder="Írd le a fontos tudnivalót...">${esc(item?.description||'')}</textarea></label><div class="info-color-label">Kártya színe</div><div class="info-color-options">${options}</div><button class="info-save" id="info-save" type="button">${item?'Mentés':'Hozzáadás'}</button></div></section>`;document.body.appendChild(host);host.querySelector('#info-cancel').onclick=close;host.querySelector('#info-modal-backdrop').onclick=close;host.querySelectorAll('[data-info-color]').forEach(b=>b.onclick=()=>{state.color=b.dataset.infoColor;host.querySelectorAll('[data-info-color]').forEach(x=>x.classList.toggle('is-selected',x===b));});host.querySelector('#info-save').onclick=()=>save(item?.id||null);host.querySelector('#info-title').focus();}
  function close(){document.getElementById('info-modal-host')?.remove();state.editingId=null;}
  async function save(id){const title=document.getElementById('info-title').value.trim();const description=document.getElementById('info-description').value.trim();if(!title||!description)return;const payload={title,description,color:state.color,created_by:currentUser(),updated_at:new Date().toISOString()};try{let q;if(id)q=await supabase.from('info_items').update(payload).eq('id',id);else q=await supabase.from('info_items').insert(payload);if(q.error)throw q.error;close();await load();}catch(e){console.error('Infó mentési hiba',e);alert('Az infó mentése nem sikerült.');}}
  async function remove(item){if(!confirm(`Biztosan törlöd ezt: „${item.title}”?`))return;try{const {error}=await supabase.from('info_items').delete().eq('id',item.id);if(error)throw error;await load();}catch(e){console.error(e);alert('Az infó törlése nem sikerült.');}}
  function show(){document.querySelectorAll('.bottom-nav-item').forEach(b=>b.classList.toggle('is-active',b.dataset.view==='info'));document.getElementById('program-list')?.classList.add('hidden');document.querySelector('.sort-bar')?.classList.add('hidden');document.getElementById('category-bar')?.classList.add('hidden');document.getElementById('placeholder-view')?.classList.remove('hidden');render();load().catch(e=>{console.error('Infók betöltési hiba',e);document.getElementById('info-list')?.replaceChildren();});}
  function init(){document.addEventListener('click',e=>{const nav=e.target.closest('.bottom-nav-item[data-view="info"]');if(nav){e.preventDefault();e.stopImmediatePropagation();show();return;}if(e.target.closest('#info-add')){modal();return;}const c=e.target.closest('.info-card');if(c&&e.target.closest('[data-info-action="menu"]')){const item=state.items.find(x=>String(x.id)===c.dataset.infoId);if(item){const choice=prompt(`„${item.title}”\n\n1 = Szerkesztés\n2 = Törlés`,'1');if(choice==='1')modal(item);if(choice==='2')remove(item);}}},true);}
  document.addEventListener('DOMContentLoaded',init);
  window.InfoView={show};
})();