create table if not exists public.info_items (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  description text not null check (char_length(trim(description)) > 0),
  color text not null default 'mint' check (color in ('mint','yellow','blue','purple','pink','gray')),
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.info_items enable row level security;

drop policy if exists info_items_select_all on public.info_items;
drop policy if exists info_items_insert_all on public.info_items;
drop policy if exists info_items_update_all on public.info_items;
drop policy if exists info_items_delete_all on public.info_items;

create policy info_items_select_all on public.info_items for select to anon, authenticated using (true);
create policy info_items_insert_all on public.info_items for insert to anon, authenticated with check (true);
create policy info_items_update_all on public.info_items for update to anon, authenticated using (true) with check (true);
create policy info_items_delete_all on public.info_items for delete to anon, authenticated using (true);

grant select, insert, update, delete on public.info_items to anon, authenticated;
grant all on public.info_items to service_role;
grant usage, select on sequence public.info_items_id_seq to anon, authenticated, service_role;
