create table if not exists public.bring_items (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 1 and 80),
  description text,
  icon_key text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bring_item_assignees (
  item_id bigint not null references public.bring_items(id) on delete cascade,
  user_name text not null,
  primary key (item_id, user_name)
);

alter table public.bring_items enable row level security;
alter table public.bring_item_assignees enable row level security;

drop policy if exists bring_items_select_all on public.bring_items;
drop policy if exists bring_items_insert_all on public.bring_items;
drop policy if exists bring_items_update_all on public.bring_items;
drop policy if exists bring_items_delete_all on public.bring_items;
create policy bring_items_select_all on public.bring_items for select to anon, authenticated using (true);
create policy bring_items_insert_all on public.bring_items for insert to anon, authenticated with check (true);
create policy bring_items_update_all on public.bring_items for update to anon, authenticated using (true) with check (true);
create policy bring_items_delete_all on public.bring_items for delete to anon, authenticated using (true);

drop policy if exists bring_item_assignees_select_all on public.bring_item_assignees;
drop policy if exists bring_item_assignees_insert_all on public.bring_item_assignees;
drop policy if exists bring_item_assignees_update_all on public.bring_item_assignees;
drop policy if exists bring_item_assignees_delete_all on public.bring_item_assignees;
create policy bring_item_assignees_select_all on public.bring_item_assignees for select to anon, authenticated using (true);
create policy bring_item_assignees_insert_all on public.bring_item_assignees for insert to anon, authenticated with check (true);
create policy bring_item_assignees_update_all on public.bring_item_assignees for update to anon, authenticated using (true) with check (true);
create policy bring_item_assignees_delete_all on public.bring_item_assignees for delete to anon, authenticated using (true);

grant select, insert, update, delete on public.bring_items to anon, authenticated;
grant select, insert, update, delete on public.bring_item_assignees to anon, authenticated;
grant usage, select on sequence public.bring_items_id_seq to anon, authenticated;
